### ISSUE TITLE
Some code correctness issues

### ISSUE THREAD

**Issue by JohnLaTwC** [jthuraisamy/TelemetrySourcerer#1]
## Issue 1
In `IsProcessElevated()`:
* Leaks TokenHandle on exit
* Fails to call FreeSid on NtAuthority
* No checks for API failures. e.g. The return from GetTokenInformation is not checked, and with ElevationType being unintialized, it could be a random value on failure.

## Issue 2a
In `LoadDriver()`:
https://github.com/jthuraisamy/TelemetrySourcerer/blob/72fd542305ee9fdfe75cdeca3f75b37787514c87/TelemetrySourcerer/KmCallbacks.cpp#L36
This call to GetModuleFileNameW is vulnerable to buffer overrun. The nSize parameter to GetModuleFileNameW should be set to MAX_PATH - 1. It is a character count of the size of the buffer ("The size of the lpFilename buffer, in TCHARs"), not a byte count which is what the code passes in.  
```diff
	WCHAR ExecutableDirectory[MAX_PATH] = { 0 };
-	GetModuleFileNameW(GetModuleHandle(NULL), (LPWSTR)&ExecutableDirectory, MAX_PATH * 2);  
+	GetModuleFileNameW(GetModuleHandle(NULL), (LPWSTR)&ExecutableDirectory, MAX_PATH - 1);  
```
	
## Issue 2b
https://github.com/jthuraisamy/TelemetrySourcerer/blob/72fd542305ee9fdfe75cdeca3f75b37787514c87/TelemetrySourcerer/KmCallbacks.cpp#L38:
This code calls `StringCbPrintfW` which is the "count of bytes" version of Printf but it passes in a count of characters (MAX_PATH). 
```diff
	WCHAR DriverPath[MAX_PATH] = { 0 };
-	StringCbPrintfW(DriverPath, MAX_PATH, LR"(\??\%ls\TelemetrySourcererDriver.sys)", ExecutableDirectory);
+	StringCchPrintfW(DriverPath, MAX_PATH, LR"(\??\%ls\TelemetrySourcererDriver.sys)", ExecutableDirectory);

```
## Issue 2c
https://github.com/jthuraisamy/TelemetrySourcerer/blob/72fd542305ee9fdfe75cdeca3f75b37787514c87/TelemetrySourcerer/KmCallbacks.cpp#L73:

None of the exit paths free the obtained resources (SCM handles, driver handle)
```diff
	if (ServiceStarted)
		return ERROR_SUCCESS;
! fails to release resources
	else
		return GetLastError();
! fails to release resources
```

## Issue 3
In `GetCallbacks(std::vector<PCALLBACK_ENTRY> OldCallbackEntries)`:
https://github.com/jthuraisamy/TelemetrySourcerer/blob/72fd542305ee9fdfe75cdeca3f75b37787514c87/TelemetrySourcerer/KmCallbacks.cpp#L281
This early exit does not free `ModuleInfos` and leaks it.  Same with `CallbackInfos`

## Issue 4
In `DriverEntry()`
https://github.com/jthuraisamy/TelemetrySourcerer/blob/72fd542305ee9fdfe75cdeca3f75b37787514c87/TelemetrySourcererDriver/TelemetrySourcererDriver.cpp#L22

The driver object is created with default permissions that allow any user to open it.  Since the driver exposes read/write primitives (`IOCTL_GET_QWORD`, `IOCTL_SET_QWORD`), this allows abuse and repurposing of this driver (esp if signed) to do anything (corrupt anything, read any secret).  A redteam using this driver would weaken the security of a system beyond the scope of modifying telemetry.

**Comment by jthuraisamy** [comment]
Thank you John, this is excellent feedback! I'll keep this thread updated with changes made to correct these issues.

For issue 4, would you recommend any other steps beyond using `IoCreateDeviceSecure`? Taking a look at the example strings [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/kernel/sddl-for-device-objects).
